[package]
name = "image-webp-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.25.5", default-features = false }
image-webp = { path = "../image-webp" }

[profile.dev]

[profile.release]
debug = true
